import mathlibData from './lib/mathlib.json';

export interface Env {
  THEOREMS_INDEX: any; // Vectorize bindings
}

const corsHeaders = {
  // Adjust this to your specific GitHub Pages domain for production
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, x-user-gemini-key',
};

export default {
  async fetch(request: Request, env: Env, ctx: any): Promise<Response> {
    // 1. Request Parsing & Guardrails
    
    // Handle CORS preflight requests
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders });
    }

    // Enforce POST requests
    if (request.method !== 'POST') {
      return new Response(JSON.stringify({ error: 'Method Not Allowed' }), {
        status: 405,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Ensure the user provided their Gemini API key headers via BYOK system
    const userKey = request.headers.get('x-user-gemini-key');
    if (!userKey) {
      return new Response(JSON.stringify({ error: 'Missing x-user-gemini-key header. 401 Unauthorized' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    try {
      // Parse the Canonical ProblemState from the incoming request body
      const body = (await request.json()) as any;
      const problemStateStr = JSON.stringify(body.problemState || body);

      // 2. Generate Embedding via User's Key using Gemini Embedding API
      const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-2:embedContent?key=${userKey}`;
      
      const embedReqBody = {
          content: {
              parts: [{ text: problemStateStr }]
          },
          outputDimensionality: 768
      };

      const embedRes = await fetch(geminiUrl, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(embedReqBody)
      });

      if (!embedRes.ok) {
          const errorText = await embedRes.text();
          return new Response(JSON.stringify({ error: 'Failed to generate embedding', details: errorText }), {
              status: embedRes.status,
              headers: { ...corsHeaders, 'Content-Type': 'application/json' }
          });
      }

      const embedData = (await embedRes.json()) as any;
      const vector = embedData.embedding?.values;

      if (!vector) {
          return new Response(JSON.stringify({ error: 'No embedding generated by Gemini.' }), {
              status: 500,
              headers: { ...corsHeaders, 'Content-Type': 'application/json' }
          });
      }

      // 3. Query Vector Database via Developer Key
      // using Cloudflare Vectorize native binding
      const dbData = await env.THEOREMS_INDEX.query(vector, {
          topK: 15
      });

      // 4. Response
      // Extract matched theorems by linking matched IDs to static mathlib
      const mathlib = mathlibData as Record<string, any>;
      const selectedTheorems = dbData.matches
        ?.map((match: any) => mathlib[match.id])
        .filter(Boolean) || [];

      // Return the theorems and DSL metadata back to the client
      return new Response(JSON.stringify({ theorems: selectedTheorems }), {
          status: 200,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });

    } catch (err: any) {
      return new Response(JSON.stringify({ error: 'Internal Server Error', details: err.message }), {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }
  }
};
